version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    working_directory: /go/src/github.com/joincivil/civil-events-crawler

    environment:

    steps:
      - run:
          name: Local docker sudo
          command: |
            if [[ $CIRCLE_BUILD_NUM -gt 0 ]]; then
              echo "This is not a local build. Disabling sudo for docker"
              touch ~/sudo
            else
              echo "This is a local build. Enabling sudo for docker"
              echo sudo > ~/sudo
            fi
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gopkg.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - run: make setup

      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "Gopkg.lock" }}

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run unit tests
          environment:
            DB_URL: "postgres://root@localhost:5432/circle_test?sslmode=disable"
            DB_MIGRATIONS: /go/src/github.com/joincivil/civil-events-crawler/migrations
          command: |
            make test
      - run: make build
      - run: make lint

      - persist_to_workspace:
          root: ./
          paths:
            - build

  setup-gcp:
    docker:
      - image: civilmedia/gcloud-node:latest
    working_directory: /go/src/github.com/joincivil/civil-events-crawler
    steps:
       - run:
          name: Dump Google Cloud Credentials to file
          command: |
            echo ${GOOGLE_AUTH} | base64 -d > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
            gcloud docker --authorize-only
       - persist_to_workspace:
          root: /root
          paths:
            - gcp-key.json
            - .config/gcloud
            - .docker
            - .dockercfg
            - .kubernetes_ns
            - .kube

  push-container:
    docker:
      - image: civilmedia/gcloud-node:latest
    working_directory: /go/src/github.com/joincivil/civil-events-crawler
    steps:
      - attach_workspace:
          at: /root
      - checkout
      - setup_remote_docker
      - run:
          name: Build Container
          command: |
            TAG=`echo $CIRCLE_BRANCH | sed 's/\\//_/g'`

            mv /root/build ./build

            docker build . \
              -t gcr.io/$GOOGLE_PROJECT_ID/$CIRCLE_PROJECT_REPONAME:$TAG \
              -t gcr.io/$GOOGLE_PROJECT_ID/$CIRCLE_PROJECT_REPONAME:$TAG-$CIRCLE_SHA1
      - deploy:
          name: Push Containers to Registry
          command: |
           gcloud config list
           echo "pushing $GOOGLE_PROJECT_ID"
           docker push gcr.io/$GOOGLE_PROJECT_ID/$CIRCLE_PROJECT_REPONAME
  deploy-staging:
    docker:
      - image: civilmedia/gcloud-node:latest
    working_directory: ~/repo
    steps:
      - attach_workspace:
              at: /root
      - deploy:
          name: Update Kubernetes Deployment on STAGING
          command: |
            kubectl set image deployment/$CIRCLE_PROJECT_REPONAME $CIRCLE_PROJECT_REPONAME=gcr.io/$GOOGLE_PROJECT_ID/$CIRCLE_PROJECT_REPONAME:development-$CIRCLE_SHA1 --namespace staging
  deploy-production:
    docker:
      - image: civilmedia/gcloud-node:latest
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /root
      - deploy:
          name: Update Kubernetes Deployment on PRODUCTION
          command: |
            echo "intentionally turned off - uncomment to enable"
            # kubectl set image deployment/$CIRCLE_PROJECT_REPONAME $CIRCLE_PROJECT_REPONAME=gcr.io/$GOOGLE_PROJECT_ID/$CIRCLE_PROJECT_REPONAME:master-$CIRCLE_SHA1 --namespace production
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - setup-gcp:
          context: gcp-common
          requires:
            - build
          filters:
            branches:
              only:
                - development
                - master
                - dankins/ch717/deploy
                - /container-.*/
      - push-container:
          context: gcp-common
          requires:
            - setup-gcp
          filters:
            branches:
              only:
                - development
                - master
                - dankins/ch717/deploy
                - /container-.*/
      - deploy-staging:
          context: gcp-common
          requires:
            - push-container
          filters:
            branches:
              only:
                - development
                - dankins/ch717/deploy
      - deploy-production:
          context: gcp-common
          requires:
            - push-container
          filters:
            branches:
              only:
                - master